name: Gửi mail lịch học mỗi ngày

on:
  schedule:
    - cron: '0 0 * * *' # Chạy lúc 7h sáng giờ Việt Nam (UTC+7 = 0h UTC)
  workflow_dispatch:     # Cho phép chạy thủ công trên GitHub

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run schedule script
        run: node schedule.js
        env:
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          SENDGRID_SENDER: ${{ secrets.SENDGRID_SENDER }}
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
